config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
  resources :tags, only: [:show]
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories, except: [:show]
    resources :posts, except: [:show, :index]
    resources :pictures, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :posts
  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :summary, :body, presence: true

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category

  mount_uploader :image, ImageUploader

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select('name, count(taggings.tag_id) as count').joins(:taggings).group('name, taggings.tag_id')
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  protected

  def check_admin
    redirect_to root_path, alert: 'У вас не прав доступа к данной странице!' unless current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController

  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.order(:name)
  end

  def create
    @category = Category.new(category_params)
    @categories = Category.order(:name)
    if @category.save
      redirect_to admin_categories_path, success: t('categories.controller.create.success')
    else
      flash.now[:danger] = t('categories.controller.create.danger')
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    @categories = Category.where("id != #{@category.id}").order(:name)
    if @category.update(category_params)
      redirect_to admin_categories_path, success: t('categories.controller.update.success')
    else
      flash.now[:danger] = t('categories.controller.update.danger')
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: t('categories.controller.destroy.success')
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::AdminController

  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok} }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  before_action :set_post, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: t('posts.controller.create.success')
    else
      flash.now[:danger] = t('posts.controller.create.danger')
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, success: t('posts.controller.update.success')
    else
      flash.now[:danger] = t('posts.controller.update.danger')
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: t('posts.controller.destroy.success')
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags, :category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: :show

  def show
    @posts = Post.where(category_id: (@category.subtree_ids)).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!

  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok} }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb category
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: 'breadcrumb-item') do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: 'breadcrumb-item active')
    result.join('').html_safe
  end

  def bootstrap_class_for name
    {
        success: 'alert-success',
        error: 'alert-danger',
        danger: 'alert-danger',
        alert: 'alert-warning',
        notice: 'alert-info'
    }[name.to_sym] || name
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/admin/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? t('.create') : t('.update')), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), admin_categories_path, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<h1><%= t('.title') %></h1>
<div class="buttons_panel">
  <%= link_to t('.link_new'), new_admin_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th><%= t('.table.name') %></th>
      <th><%= t('.table.parent') %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= category.name %></td>
        <td><%= category.parent.name if category.parent.present? %></td>
        <td>
          <%= link_to t('.table.edit'), edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to t('.table.destroy'), admin_category_path(category), method: :delete, data: { confirm: t('.table.confirm')}, class: 'btn btn-outline-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @post], html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? t('.create') : t('.update')), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/admin/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? t('.create') : t('.update')), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>
<div class="buttons_panel">
  <%= link_to t('.link_new'), new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th><%= t('.table.name') %></th>
      <th><%= t('.table.parent') %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= category.name %></td>
        <td><%= category.parent.name if category.parent.present? %></td>
        <td>
          <%= link_to t('.table.edit'), edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to t('.table.destroy'), category_path(category), method: :delete, data: { confirm: t('.table.confirm')}, class: 'btn btn-outline-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/categories/show.html.erb
<%= render 'shared/breadcrumb', category: @category %>
<h1><%= @category.name %></h1>

<section id="posts">
  <%= render @posts %>
</section>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer', class: "navigation" %>

app/views/categories/show.js.erb
$('#posts').append("<%= j render partial: 'posts/delimeter' %>");
$('#posts').append("<%= j render @posts %>");

<% if @posts.next_page %>
$('.navigation').replaceWith("<%= j will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer', class: 'navigation' %>");
<% else %>
$('.navigation').remove();
<% end %>

app/views/posts/_delimeter.html.erb
<div class="page-delimeter"><%= t('.pages') + params[:page] %></div>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit t('.submit', action: @post.new_record? ? t('.create') : t('.update')), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title,  post_path(post) %></h2>
    <small><time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time></small>
    <% if post.category.present? %>
      |
      <%= link_to post.category.name, post.category %>
    <% end %>
    <% if user_signed_in? && current_user.admin? %>
      |
      <%= link_to t('.edit'), edit_admin_post_path(post) %>
      |
      <%= link_to t('.destroy'), admin_post_path(post), method: :delete, data: { confirm: t('.confirm') } %>
    <% end %>
  </section>
  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>
  <section class="post-footer">
    <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t), class: 'badge badge-primary' }.join(' ') %>
  </section>
</article>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to t('main_nav.new_post'), new_admin_post_path, class: 'btn btn-outline-primary btn-sm' %>
<% end %>

<section id="posts">
  <%= render @posts %>
</section>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer', class: "navigation" %>

app/views/posts/index.js.erb
$('#posts').append("<%= j render partial: 'delimeter' %>");
$('#posts').append("<%= j render @posts %>");

<% if @posts.next_page %>
  $('.navigation').replaceWith("<%= j will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer', class: 'navigation' %>");
<% else %>
  $('.navigation').remove();
<% end %>

app/views/posts/show.html.erb
<%= render 'shared/breadcrumb', category: @post.category %>
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small><time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time></small>
    <% if @post.category.present? %>
      |
      <%= link_to @post.category.name, @post.category %>
    <% end %>
    <% if user_signed_in? && current_user.admin? %>
      |
      <%= link_to 'Изменить', edit_admin_post_path(@post) %>
      |
      <%= link_to 'Удалить', admin_post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
    <% end %>
  </section>
  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
  <h2><%= t('.empty') %></h2>
<% else %>
  <%= render @tag.posts %>
<% end %>